package com.ferret.database.mapper

import com.ferret.database.entity.NetworkRecordEntity
import com.ferret.model.NetworkRecord

internal fun NetworkRecord.toEntity() = NetworkRecordEntity(
    id = id,
    sessionId = sessionId,
    requestDate = requestDate,
    responseDate = responseDate,
    tookMs = tookMs,
    protocol = protocol,
    method = method,
    url = url,
    host = host,
    path = path,
    scheme = scheme,
    responseTlsVersion = responseTlsVersion,
    responseCipherSuite = responseCipherSuite,
    requestPayloadSize = requestPayloadSize,
    requestContentType = requestContentType,
    requestHeaders = requestHeaders,
    requestHeadersSize = requestHeadersSize,
    requestBody = requestBody,
    isRequestBodyEncoded = isRequestBodyEncoded,
    responseCode = responseCode,
    responseMessage = responseMessage,
    error = error,
    responsePayloadSize = responsePayloadSize,
    responseContentType = responseContentType,
    responseHeaders = responseHeaders,
    responseHeadersSize = responseHeadersSize,
    responseBody = responseBody,
    isResponseBodyEncoded = isResponseBodyEncoded,
)

internal fun NetworkRecordEntity.toDomain() = NetworkRecord(
    id = id,
    sessionId = sessionId,
    requestDate = requestDate,
    responseDate = responseDate,
    tookMs = tookMs,
    protocol = protocol,
    method = method,
    url = url,
    host = host,
    path = path,
    scheme = scheme,
    responseTlsVersion = responseTlsVersion,
    responseCipherSuite = responseCipherSuite,
    requestPayloadSize = requestPayloadSize,
    requestContentType = requestContentType,
    requestHeaders = requestHeaders,
    requestHeadersSize = requestHeadersSize,
    requestBody = requestBody,
    isRequestBodyEncoded = isRequestBodyEncoded,
    responseCode = responseCode,
    responseMessage = responseMessage,
    error = error,
    responsePayloadSize = responsePayloadSize,
    responseContentType = responseContentType,
    responseHeaders = responseHeaders,
    responseHeadersSize = responseHeadersSize,
    responseBody = responseBody,
    isResponseBodyEncoded = isResponseBodyEncoded,
)
